name: Check OpenList Version

on:
  schedule:
    - cron: "0 5,17 * * *" # 每日5点和17点执行
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "sync_openlist.yaml"  

permissions:
  contents: write
  actions: write

jobs:
  check_and_update:
    runs-on: ubuntu-latest
    outputs:
      openlist_update: ${{ steps.set_output.outputs.openlist_update }}
      openlist_version: ${{ steps.set_output.outputs.openlist_version }}
    env:
      VERSION_FILE: ${{ github.workspace }}/openlist_version
    steps:
      - uses: actions/checkout@v3
      
      - name: Check OpenList Version
        run: |
          cd $GITHUB_WORKSPACE/.github/scripts
          chmod +x ./*.sh

          touch ${{ env.VERSION_FILE }}
          ./check_openlist.sh

      - name: Set Output Variables
        id: set_output
        run: |
          echo "openlist_version=${{ env.openlist_version }}" >> $GITHUB_OUTPUT
          echo "openlist_update=${{ env.openlist_update }}" >> $GITHUB_OUTPUT
          echo "OpenList Version: ${{ env.openlist_version }}"
          echo "Update Required: ${{ env.openlist_update }}"

      - name: Update Version Files
        if: env.openlist_update == '1'
        run: |
          echo -e "[自动同步OpenList] ${{ env.openlist_version }}\n\n[Auto Sync OpenList] ${{ env.openlist_version }}" > $GITHUB_WORKSPACE/CHANGELOG.md
          echo -e "${{ env.openlist_version }}" > ${{ env.VERSION_FILE }}
          
          chmod +x $GITHUB_WORKSPACE/.github/scripts/update_pubspec_version.sh
          $GITHUB_WORKSPACE/.github/scripts/update_pubspec_version.sh

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[bot] Update openlist to ${{ env.openlist_version }}"
          git push

  build_openlist_libraries:
    needs: [check_and_update]
    if: needs.check_and_update.outputs.openlist_update == '1'
    uses: ./.github/workflows/build_openlist.yaml

  trigger_release:
    needs: [check_and_update, build_openlist_libraries]
    if: needs.check_and_update.outputs.openlist_update == '1' && ( success() || failure() )
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release Workflow
        run: |
          echo "OpenList libraries built successfully, triggering release workflow..."
          gh workflow run release.yaml -R OpenListTeam/OpenList-Mobile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
